/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.JavaFundamental;

public class App {
    public static void main(String[] args) {
        // Contoh 1.1 dari Modul Pemrograman Lanjut
        System.out.println("Hallo Covid-19");
    }
}
